### PR TITLE
shebanq.yml added

### PR DESCRIPTION
**Pull request by dirkroorda**
N.B. I added multiple sources in list form to under `source:`. Not sure whether that is supported.

### CODE REVIEW

**Comment by proycon** [comment]
No, the idea is to have one source that describes the application best, that one source's metadata can in turn explicitly refer to other sources as dependencies. If you want the others included in the tool discovery process as well (that assumes they each have some standalone potential), add a separate yaml file for each.

Multiple services are allowed (because one tool can be hosted in multiple locations).

**Comment by proycon** [comment]
I added some clearer contributing instructions now: https://github.com/CLARIAH/tool-discovery/blob/master/CONTRIBUTING.md

**Review by dirkroorda — COMMENTED** [review]
I deleted several hebrew data repositories. Now there is just shebanq.yml left.

**Comment by proycon** [comment]
Thanks, merged!

**Pull request merged**
